sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - ADAPTER_DEPS="alcaeus/mongo-php-adapter"
    - MONGO_DRIVER=mongo

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
        - MONGO_DRIVER=mongodb
    - php: 7
      env:
        - DEPS=locked
        - CS_CHECK=true
        - MONGO_DRIVER=mongodb
    - php: 7
      env:
        - DEPS=latest
        - MONGO_DRIVER=mongodb
    - php: 7.1
      env:
        - DEPS=lowest
        - MONGO_DRIVER=mongodb
    - php: 7.1
      env:
        - DEPS=locked
        - CS_CHECK=true
        - MONGO_DRIVER=mongodb
    - php: 7.1
      env:
        - DEPS=latest
        - MONGO_DRIVER=mongodb

services: mongodb

before_install:
  - travis_retry composer self-update

install:
  - yes '' | pecl -q install -f $MONGO_DRIVER
  - if [[ $MONGO_DRIVER == 'mongodb' ]]; then travis_retry composer config "platform.ext-mongo" "1.6.16" && composer require --dev $COMPOSER_ARGS $ADAPTER_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show
  - if ! nc -z localhost 27017; then sudo service mongod start; fi

script:
  - if [[ $DEPS == 'lowest' ]]; then cp ./tests/TestConfigurationV2.php ./config/application.config.php ; else cp ./tests/TestConfigurationV3.php ./config/application.config.php ; fi
  - ./vendor/bin/doctrine-module odm:schema:create
  - ./vendor/bin/doctrine-module odm:schema:drop
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; else ./vendor/bin/phpunit ; fi
  - if [[ $CHECK_CS == 'true' ]]; then ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ ./config/ ; fi
